language: groovy
jdk:
  - oraclejdk7

before_script: 
     - export DISPLAY=:99.0
     - sh -e /etc/init.d/xvfb start
     - sleep 5 # give xvfb some time to start

script: 
  - ./grailsw refresh-dependencies
# We can't use Geb and Travis-ci… We must have an X-Server for firefox launching
  - ./grailsw "test-app -integration -unit -coverage -xml" 

after_success:
  - ./grailsw coveralls

deploy:
    provider: heroku
    api_key:
        secure: cdcfb04e-c7ce-4983-a932-654045db6e54
    on: master
    app: m2dl-bandstorm

